include:
  - ./user-server/docker-compose.yml
  - ./auth-server/docker-compose.yml

services:
  eureka:
    build:
      context: ./eureka-demo
      dockerfile: Dockerfile
    networks:
       - eureka-network
  gateway:
    build:
      context: ./api-gateway-demo
      dockerfile: Dockerfile
    depends_on:
       - eureka
    networks:
       - eureka-network
    ports:
       - "8080:8080"

networks:
  eureka-network:
    driver: bridge