services:
  user_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - report-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: report
    #    depends_on:
    #       - eureka
    links:
      - "user_db:database"
    ports:
      - "8080:8080"
    networks:
      - report-network

networks:
  user-network:
    driver: bridge