-- Generated by the database client.

CREATE TYPE user_role_enum AS ENUM ('user', 'admin', 'super_user');
CREATE TABLE credentials(
    id integer NOT NULL,
    role user_role_enum,
    username varchar(255),
    password_hash varchar(255),
    PRIMARY KEY(id)
);