-- Generated by the database client.
CREATE TABLE credentials(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    role user_role_enum,
    username varchar(255),
    password_hash varchar(255),
    PRIMARY KEY(id)
);