services:
  auth_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
    networks:
       - auth-network
  auth_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
       - eureka
    links:
       - "auth_db:database"
#    ports:
#      - "8081:8081"
    networks:
      - auth-network
      - eureka-network
  
networks:
  auth-network:
    driver: bridge